SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN (
    SELECT *
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
) S ON B.BOOK_ID = S.BOOK_ID
GROUP BY 2, 3
ORDER BY 1, 3 DESC;