WITH U2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED >= '2021-01-01'
      AND JOINED < '2022-01-01'
),
TOT AS (
    SELECT COUNT(*) AS TOTAL_USERS
    FROM U2021
)
SELECT
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / TOT.TOTAL_USERS, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE O
JOIN U2021 U
  ON O.USER_ID = U.USER_ID
CROSS JOIN TOT
GROUP BY 1, 2
ORDER BY 1, 2;