SELECT
    (
        IF(MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3,
          '1Q', IF(MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6,
          '2Q', IF(MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9,
          '3Q', '4Q')))
    ) AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY 1
ORDER BY 1;