SELECT
    U.USER_ID,
    U.NICKNAME,
    SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE (BOARD_ID, WRITER_ID) IN (
    SELECT BOARD_ID, WRITER_ID
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
)
GROUP BY 1, 2
HAVING SUM(B.PRICE) >= 700000
ORDER BY 3;