SELECT
    A.MEMBER_NAME,
    B.REVIEW_TEXT,
    DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW B
LEFT JOIN MEMBER_PROFILE A ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_NAME = (
    SELECT A.MEMBER_NAME
    FROM REST_REVIEW B
    LEFT JOIN MEMBER_PROFILE A ON A.MEMBER_ID = B.MEMBER_ID
    GROUP BY 1
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY 3, 2;