SELECT
    YEAR(A.DIFFERENTIATION_DATE) AS YEAR,
    (B.MAXSIZE - A.SIZE_OF_COLONY) AS YEAR_DEV,
    A.ID
FROM ECOLI_DATA A
LEFT JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXSIZE
    FROM ECOLI_DATA
    GROUP BY 1
) B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY 1, 2;