SELECT C.ID, B.FISH_NAME, A.LENGTH
FROM (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY 1
) A
LEFT JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
JOIN FISH_INFO C
ON A.FISH_TYPE = C.FISH_TYPE AND A.LENGTH = C.LENGTH
ORDER BY 1;