SELECT
    SUM(G.SCORE) AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM HR_EMPLOYEES E
LEFT JOIN HR_DEPARTMENT D ON D.DEPT_ID = E.DEPT_ID
LEFT JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY 2
ORDER BY 1 DESC
LIMIT 1;